# Generated by Django 2.2.4 on 2022-08-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhpy', '0003_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
