# Generated by Django 2.2.4 on 2022-08-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhpy', '0006_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='top_fixed',
            field=models.BooleanField(default=True),
        ),
    ]
